spring.application.name=mh_sunbreak_simulator

spring.datasource.url=jdbc:postgresql://localhost:5432/mh_sunbreak_simulator

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

mybatis.mapper-locations=classpath:mapper/*.xml
